backend:
  name: git-gateway
  repo: ponytojas/Fagolambda
  branch: stagging 
publish_mode: editorial_workflow
media_folder: "images/uploads" 
public_folder: "/images/uploads"

collections:
  - name: "article" 
    label: "Artículo" # Used in the UI
    folder: "_posts/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string", default: "Lorena Jiménez"}
      - {label: "Tiempo de lectura", name: "time-to-read", widget: "string"}
      - {label: "Imagen de cabecera", name: "thumbnail", widget: "image", required: false}
      - {label: "Subtítulo", name: "subtitle", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Etiquetas", name: "tags", widget: "list"}